### ISSUE TITLE
サンプルデータに関して

### ISSUE THREAD

**Issue by kamiyatakumi0918** [Hirochon/GCI2020-Summer#1]
@Hirochon さん こんにちは。

コード内で、train.csvなどいくつかのサンプルデータやファイルを読み込んでいるかと思うのですが、それらのファイルがアップロードされていないため、実際にコードを動かして確認すると言ったことができません。もしよろしければ、読み込んでいるファイルに関してGitHubであげていただきたいです。

**Comment by Hirochon** [comment]
@kamiyatakumi0918 

まずリポジトリを見て頂きありがとうございます！
csvファイルなどのデータに関してですが、機密保持契約の上で扱っているため、
コードをGitHubにあげることができません、、、！

データは個人で取りに行けるので、それを取りに行っていただければと思います！

**Comment by kamiyatakumi0918** [comment]
@Hirochon 
ありがとうございます。
> なのでデータは個人で取りに行けるので、それを取りに行っていただければと思います！

この部分がよくわからないので、説明していただけると幸いです

**Comment by Hirochon** [comment]
@kamiyatakumi0918 
一部データはKaggleから提供されているというとこですね！

**Comment by Hirochon** [comment]
クローズします
